### ISSUE TITLE
Adding a disciption in README.md

### ISSUE THREAD

**Issue by shivankgtm** [pyjaipur/Getting-Started#2]
I found a great book for Python online [here](https://books.goalkicker.com/PythonBook/
). as an issue you need to add a small description of the book content with the link to the book.
This book contains a lot of Python more than just basic syntax. so putting the description in 'B' Section (you need to add it 'A' - 'Basic Python Syntax' is already there)

**Comment by Maheima** [comment]
i want to be a part of it

**Comment by Man-Jain** [comment]
@Shivank98 Please assign it to me.I will do it.  :)

**Comment by shivankgtm** [comment]
I am assigning @Maheima  on this issue on the basis of FCFS. @Maheima do you have a deadline in mind?

**Comment by Maheima** [comment]
I have not worked on anything like this before so, first i would like to
know how to get started and what all knowledge is required to touch this
task.

**Comment by shivankgtm** [comment]
First, you need to learn Git and Github [here is a CheatSheet](https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf)
after that basic of Markdown language.
in steps

1. fork the [repo](https://github.com/pyjaipur/Getting-Started).

2. clone your forked repo.

3. make desired changes in [README.md](https://github.com/pyjaipur/Getting-Started/blob/master/README.md) using [markdown](https://guides.github.com/features/mastering-markdown/)

4. push it in your forked repo.

5. from there make pull request.


feel free to ask :)

**Comment by Maheima** [comment]
Thanks for this link and the guide. I will go through this and try to start
it asap.

**Comment by Man-Jain** [comment]
Np @Shivank98 :)

**Comment by shivankgtm** [comment]
@Maheima Any progress ?

**Comment by shivankgtm** [comment]
congratulation @Maheima on your first contribution, Welcome to OpenSource :)

**Comment by Maheima** [comment]
is it done now?

**Comment by shivankgtm** [comment]
yes you can see changes on main repo.

**Comment by Maheima** [comment]
Thanks for giving me this opportunity :)
